kind: pipeline
name: Rave

clone:
  depth: 1

steps:
- name: Building
  image: fadlyas/kernel_dockerfile
  environment:
    bot_token:
      from_secret: BOT_API_KEY
    chat_id:
      from_secret: CHAT_ID
  image: archlinux:base-devel
  commands:
  - curl -LO "https://repo.archlinuxcn.org/x86_64/glibc-linux4-2.33-4-x86_64.pkg.tar.zst" && bsdtar -C / -xvf "glibc-linux4-2.33-4-x86_64.pkg.tar.zst"
  - pacman -Sy && pacman -S git bc inetutils python2 zip wget cpio jdk-openjdk tzdata --noconfirm
  - ln -s /usr/share/zoneinfo/Europe/Rome /etc/localtime && date
  - bash ./build.sh
